name: General checks

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-code:
    uses: Lightning-AI/utilities/.github/workflows/check-code.yml@v0.8.0
    with:
      actions-ref: v0.7.1

  check-schema:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@v0.8.0
    with:
      azure-dir: ".azure"

  check-package:
    uses: Lightning-AI/utilities/.github/workflows/check-package.yml@v0.8.0
    with:
      actions-ref: v0.7.1
      import-name: "lightning_colossalai"
      artifact-name: dist-packages-${{ github.sha }}
      testing-matrix: |
        {
          "os": ["ubuntu-latest", "macos-latest", "windows-latest"],
          "python-version": ["3.9"]
        }

  check-docs:
    uses: Lightning-AI/utilities/.github/workflows/check-docs.yml@v0.8.0
    with:
      requirements-file: "_requirements/docs.txt"
